---
- name: group by 
  hosts: all
  tasks: 
    - name: group host by app_type
      action: group_by key=${ansible_distribution}-${ansible_distribution_version}


    - name: message by groups
      debug: msg="groups={{groups}}"
      run_once: true
