---
- name: group by 
  hosts: all
  tasks: 
    - name: group host by app_type
      group_by: key={{ ansible_lsb }}

    - name: message by groups
      debug: msg="groups={{groups}}"
      run_once: true
