---
- hosts: lb01
  become: true
  tasks:
    - name: verify nginx service
      command: systemctl status nginx

    - name: verify nginx is listening on 80
      wait_for:
        port: 80
        timeout: 1

- hosts: app
  become: true
  tasks:
    - name: verify apache2 service
      command: systemctl status apache2

    - name: verify apache2 is listening on 80
      wait_for:
        port: 80
        timeout: 1

- hosts: db01
  become: true
  tasks:
    - name: verify mysql service
      command: systemctl status mysql

    - name: verify mysql is listening on 80
      wait_for:
        port: 3306
        timeout: 1

- hosts: localhost
  become: true
  tasks:
    - name: verify end-to-end response
      uri: url=http://{{item}} return_content=yes
      with_items: groups.lb01
      register: lb_index

    - fail: msg="index failed to return content"
      when: "'Hello, from sunny' not in item.content"
      with_items: "{{lb_index.results}}"