---
# Bring stack down |  always start bringing down from loadbalancer front end
- hosts: lb01
  become: true
  tasks:
    - service: 
        name: nginx
        state: stopped

- hosts: app
  become: true
  tasks:
    - service: 
        name: apache2
        state: stopped
        
# database is restarted and not stopped because since we are starting up services we need database to bootstrap the app once is back
- hosts: db01
  become: true
  tasks:
    - service: 
        name: mysql
        state: restarted
# Bring stack up 
- hosts: app
  become: true
  tasks:
    - service: 
        name: apache2
        state: started

- hosts: lb01
  become: true
  tasks:
    - service: 
        name: nginx
        state: started

