---
# Bring stack down
- hosts: lb01
  become: true
  tasks:
    - service: 
        name: nginx
        state: stopped

- hosts: app
  become: true
  tasks:
    - service: 
        name: apache2
        state: stopped
        
- hosts: db01
  become: true
  tasks:
    - service: 
        name: mysql
        state: restarted
# Bring stack up 
- hosts: app
  become: true
  tasks:
    - service: 
        name: apache2
        state: started
        
- hosts: lb01
  become: true
  tasks:
    - service: 
        name: nginx
        state: started

