---
- hosts: lb01
  become: true
  tasks:
    - name: verify nginx service
      command: systemctl status nginx

- hosts: app
  become: true
  tasks:
    - name: verify apache2 service
      command: systemctl status apache2

- hosts: db01
  become: true
  tasks:
    - name: verify mysql service
      command: systemctl status mysql