---
- hosts: app
  become: true
  tasks:
    - name: install apache2
      apt: 
        name: {{ item }}
        state: present
        update_cache: yes
      loop:
        - apache2
        - libapache2-mod-wsgi
        - python-pip
        - python-virtualenv

        