---
- hosts: app
  become: true
  tasks:
    - name: install apache2
      apt: 
        name: {{ packages }}
        state: present
        update_cache: yes
      vars:
        packages:
          - apache2
          - libapache2-mod-wsgi
          - python-pip
          - python-virtualenv

