---
- hosts: app
  become: true
  tasks:
    - name: PHP | Install Ondrej PHP PPA
      apt_repository: 
        repo: 'ppa:ondrej/php' 
        update_cache: yes
        
    - name: install web components
      apt: 
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - apache2
          - libapache2-mod-wsgi
          - python-pip
          - python-virtualenv
          - php7.2

    - name: ensure apache2 started
      service: 
        name: apache2
        state: started
        enabled: yes

    - name: ensure mod_wsgi enabled
      apache2_module: 
        state: present
        name: wsgi
      notify: restart apache2

  handlers:
    - name: restart apache2
      service: 
        name: apache2
        state: restarted
