---
- name: PHP | Install Ondrej PHP PPA
  apt_repository: 
    repo: 'ppa:ondrej/php'
  tags: [ 'packages' ]    
        
- name: install web components
  apt: 
    name: "{{ packages }}"
    state: present    
  vars:
    packages:
      - apache2
      - libapache2-mod-wsgi
      - python-pip
      - python-virtualenv
      - php7.2
      - python-mysqldb
      - python-httplib2
      - curl
  tags: [ 'packages' ]

- name: ensure mod_wsgi installed
  apache2_module: 
    state: present
    name: wsgi
  notify: restart apache2

- name: de-activate default apache site
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify: restart apache2 
    