---
- name: PHP | Install Ondrej PHP PPA
  apt_repository: 
    repo: 'ppa:ondrej/php' 
    update_cache: yes
        
- name: install web components
  apt: 
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - apache2
      - libapache2-mod-wsgi
      - python-pip
      - python-virtualenv
      - php7.2
      - python-mysqldb
      - python-httplib2
      - curl 

- name: ensure mod_wsgi installed
  apache2_module: 
    state: present
    name: wsgi
  notify: restart apache2

- name: de-activate default apache site
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify: restart upstream {{ item.key }} {
{% for server in groups.app %}
    server {{ server }}:{{ item.value.backend }};
{% endfor %}
}

server {
    listen {{ item.value.frontend }};

    location / {
        proxy_pass http://{{ item.key }};
    }
}

- name: ensure apaupstream {{ item.key }} {
{% for server in groups.app %}
    server {{ server }}:{{ item.value.backend }};
{% endfor %}
}

server {
    listen {{ item.value.frontend }};

    location / {
        proxy_pass http://{{ item.key }};
    }
}
  service: 
    name: apache2
    state: startedupstream {{ item.key }} {
{% for server in groups.app %}
    server {{ server }}:{{ item.value.backend }};
{% endfor %}
}

server {
    listen {{ item.value.frontend }};

    location / {
        proxy_pass http://{{ item.key }};
    }
}
    enabled: yes